# 编译打包、生成Docker镜像并推送到DockerHub上
name: DockerHub

# 触发条件，手工执行
on: workflow_dispatch

# 全局环境变量
env:
  NAME: media
  BRANCH: master

# 步骤流程：
jobs:
  release:
    name: Build Project
    runs-on: ubuntu-latest
    outputs:
      download_url: ${{ steps.release_upload.outputs.browser_download_url }}
    steps:
      # 1. 拉取代码
      - uses: actions/checkout@v3
        with:
          ref: ${{env.BRANCH}}
      # 2. 准备编译环境
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17.0.7'
          distribution: 'graalvm' # See 'Options' for all available distributions
          github-token: ${{ secrets.GITHUB_TOKEN }}
      # 3. 环境验证
      - name: Example step
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version
      # 4. 编译项目
      - name: Example step using Maven plugin  # https://graalvm.github.io/native-build-tools/latest/maven-plugin.html
        run: mvn -Pnative package